Recipes/RecipesApp/Controllers/AuthController.cs
using DataContracts.Entities;
using Microsoft.AspNetCore.Authentication;
using Microsoft.AspNetCore.Authentication.Cookies;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Hosting;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Localization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Configuration;
using RecipesApp.Models.FormModels;
using System;
using System.Collections.Generic;
using System.Security.Claims;
using System.Threading.Tasks;
using static ModelsLibrary.Constants.AppConstants;

namespace RecipesApp.Controllers;

[Route("auth")]
public sealed class AuthController : MyBaseController
{
    public AuthController(IConfiguration config, IWebHostEnvironment env) : base(config, env) { }

    [HttpGet("login")]
    public IActionResult Login(string r)
    {
        HandleViewData();
        ViewData["url"] = r;
        return View(new AuthFormModel());
    }

    [HttpPost("signin")]
    [ValidateAntiForgeryToken]
    public async Task<IActionResult> SignIn(AuthFormModel model)
    {
        if (!ModelState.IsValid) return View("Login", model);
        string issuer = Request.Host.Value;
        await ApiAuthAsync();
        IUser user = await dal.LoginAsync(model.Username, model.Password);
        
        if (user is null)
        {
            ViewData["url"] = Request.Form["url"];
            ViewData["Error"] = translation[I18N.Authentication_failed];
            return View("Login");
        }

        List<Claim> claims = new List<Claim>
        {
            new Claim("ID", user.ID.ToString(), ClaimValueTypes.String, issuer),
            new Claim(ClaimTypes.Name, user.Username, ClaimValueTypes.String, issuer),
            new Claim("Name", user.Name, ClaimValueTypes.String, issuer),
        };
        foreach (var role in user.Roles)
        {
            claims.Add(new Claim(ClaimTypes.Role, role.Name, ClaimValueTypes.String, issuer));
        }
        var userIdentity = new ClaimsIdentity("SuperSecureLogin");
        userIdentity.AddClaims(claims);
        var user_principal = new ClaimsPrincipal(userIdentity);
        await HttpContext.SignInAsync(CookieAuthenticationDefaults.AuthenticationScheme, user_principal, new AuthenticationProperties
        {
            ExpiresUtc = DateTime.UtcNow.AddHours(10),
            IsPersistent = true,
            AllowRefresh = true,
        });
        Response.Cookies.Append(
           CookieRequestCultureProvider.DefaultCookieName,
           CookieRequestCultureProvider.MakeCookieValue(new RequestCulture(user.PreferedCulture)),
           new CookieOptions { Expires = DateTime.Now.AddYears(1) });
        string return_url = string.IsNullOrWhiteSpace(HttpContext.Request.Form["url"].ToString()) ? "/" : HttpContext.Request.Form["url"].ToString();
        return Redirect(return_url);

    }

    [HttpPost("logout")]
    [ValidateAntiForgeryToken]
    [Authorize]
    public async Task<IActionResult> Logout()
    {
        await HttpContext.SignOutAsync();
        HttpContext.Session.Clear();
        return Redirect("/");
    }

    [HttpGet("forbidden")]
    public IActionResult Forbidden()
    {
        return View();
    }

}

Recipes/RecipesApp/Controllers/ExportController.cs
using DataContracts.Entities;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Hosting;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Configuration;
using ModelsLibrary.Constants;
using Newtonsoft.Json;
using QuestPDF.Fluent;
using RecipesApp.Models.FormModels;
using RecipesApp.Services;
using System;
using System.Collections.Generic;
using System.Data;
using System.IO;
using System.Linq;
using System.Threading.Tasks;
using I18N = ModelsLibrary.Constants.AppConstants.I18N;

namespace RecipesApp.Controllers;

[Route("export")]
[Authorize]
public class ExportController : MyBaseController
{
    public ExportController(IConfiguration configuration, IWebHostEnvironment environment) : base(configuration, environment) { }

    [HttpGet]
    public IActionResult ExportForm()
    {
        HandleViewData();
        return View(new ExportFormModel());
    }

    [HttpPost]
    [ValidateAntiForgeryToken]
    public async Task<IActionResult> ExportAsync(ExportFormModel model)
    {
        #region paths
        string export_path = model.ModelType switch
        {
            AppConstants.Model.Author => EnvironmentSetup.AuthorExportPath,
            AppConstants.Model.Category => EnvironmentSetup.CategoryExportPath,
            AppConstants.Model.Country => EnvironmentSetup.CountryExportPath,
            AppConstants.Model.Course => EnvironmentSetup.CourseExportPath,
            AppConstants.Model.Ingredient => EnvironmentSetup.IngredientExportPath,
            AppConstants.Model.Recipe => EnvironmentSetup.RecipeExportPath,
            AppConstants.Model.Region => EnvironmentSetup.RegionExportPath,
            AppConstants.Model.Source => EnvironmentSetup.SourceExportPath,
            _ => throw new Exception("Invalid model"),
        };
        string file_extension = model.ExportType switch
        {
            AppConstants.ExportTypes.Pdf => "pdf",
            AppConstants.ExportTypes.Json => "json",
            AppConstants.ExportTypes.Excel => "xlsx",
            _ => throw new Exception("Invalid export type")
        };
        string file_type = model.ExportType switch
        {
            AppConstants.ExportTypes.Pdf => "application/pdf",
            AppConstants.ExportTypes.Json => "application/json",
            AppConstants.ExportTypes.Excel => "application/vnd.openxmlformats-officedocument.spreadsheetml.sheet",
            _ => throw new Exception("Invalid export type")
        };
        string filename = $"{DateTime.Now.Ticks}.{file_extension}";
        string file_path_name = Path.Combine(export_path, filename);

        #endregion
        await ApiAuthAsync();

        try
        {
            switch (model.ExportType)
            {
                case AppConstants.ExportTypes.Json:
                    #region Json
                    Formatting formatting = Formatting.None;
                    switch (model.ModelType)
                    {
                        case AppConstants.Model.Author:
                            System.IO.File.WriteAllText(file_path_name, JsonConvert.SerializeObject(await dal.SelectAllAuthorsAsync(), formatting));
                            break;
                        case AppConstants.Model.Category:
                            System.IO.File.WriteAllText(file_path_name, JsonConvert.SerializeObject(await dal.SelectAllCategoriesAsync(), formatting));
                            break;
                        case AppConstants.Model.Country:
                            System.IO.File.WriteAllText(file_path_name, JsonConvert.SerializeObject(await dal.SelectAllCountriesAsync(), formatting));
                            break;
                        case AppConstants.Model.Course:
                            System.IO.File.WriteAllText(file_path_name, JsonConvert.SerializeObject(await dal.SelectAllCoursesAsync(), formatting));
                            break;
                        case AppConstants.Model.Ingredient:
                            System.IO.File.WriteAllText(file_path_name, JsonConvert.SerializeObject(await dal.SelectAllIngredientsAsync(), formatting));
                            break;
                        case AppConstants.Model.Recipe:
                            IEnumerable<IRecipe> recipes = await dal.SelectAllRecipesAsync();
                            for (int i = 0; i < recipes.Count(); i++)
                            {
                                IRecipe recipe = recipes.ElementAt(i);
                                recipe.Ingredients = await dal.SelectAllRecipeIngredientsAsync(recipe);
                            }
                            System.IO.File.WriteAllText(file_path_name, JsonConvert.SerializeObject(await dal.SelectAllRecipesAsync(), formatting));
                            break;
                        case AppConstants.Model.Region:
                            System.IO.File.WriteAllText(file_path_name, JsonConvert.SerializeObject(await dal.SelectAllRegionsAsync(), formatting));
                            break;
                        case AppConstants.Model.Source:
                            System.IO.File.WriteAllText(file_path_name, JsonConvert.SerializeObject(await dal.SelectAllRecipeSourceAsync(), formatting));
                            break;
                        default:
                            break;
                    }
                    #endregion
                    break;
                case AppConstants.ExportTypes.Excel:
                    #region Excel
                    DataTable table = null;
                    switch (model.ModelType)
                    {
                        case AppConstants.Model.Author:
                            IEnumerable<IAuthor> authors = await dal.SelectAllAuthorsAsync();
                            table = ModelsLibrary.Models.Author.ExportToDataTable(authors);
                            break;
                        case AppConstants.Model.Category:
                            IEnumerable<ICategory> categories = await dal.SelectAllCategoriesAsync();
                            table = ModelsLibrary.Models.Category.ExportToDataTable(categories);
                            break;
                        case AppConstants.Model.Country:
                            IEnumerable<ICountry> countries = await dal.SelectAllCountriesAsync();
                            table = ModelsLibrary.Models.Country.ExportToDataTable(countries);
                            break;
                        case AppConstants.Model.Course:
                            IEnumerable<ICourse> courses = await dal.SelectAllCoursesAsync();
                            table = ModelsLibrary.Models.Course.ExportToDataTable(courses);
                            break;
                        case AppConstants.Model.Ingredient:
                            IEnumerable<IIngredient> ingredients = await dal.SelectAllIngredientsAsync();
                            table = ModelsLibrary.Models.Ingredient.ExportToDataTable(ingredients);
                            break;
                        case AppConstants.Model.Recipe:
                            IEnumerable<IRecipe> recipes = await dal.SelectAllRecipesAsync();
                            table = ModelsLibrary.Models.Recipe.ExportToDataTable(recipes);
                            break;
                        case AppConstants.Model.Region:
                            IEnumerable<IRegion> regions = await dal.SelectAllRegionsAsync();
                            table = ModelsLibrary.Models.Region.ExportToDataTable(regions);
                            break;
                        case AppConstants.Model.Source:
                            IEnumerable<ISource> sources = await dal.SelectAllRecipeSourceAsync();
                            table = ModelsLibrary.Models.Source.ExportToDataTable(sources);
                            break;
                        default:
                            throw new NotImplementedException();
                    }
                    if (table is not null)
                    {
                        ExcelExportService.Export(file_path_name, table);
                    }
                    #endregion
                    break;
                case AppConstants.ExportTypes.Pdf:
                    #region Pdf
                    Document document = model.ModelType switch
                    {
                        AppConstants.Model.Author => PdfExport.ExportList(await dal.SelectAllAuthorsAsync()),
                        AppConstants.Model.Category => PdfExport.ExportList(await dal.SelectAllCategoriesAsync()),
                        AppConstants.Model.Country => PdfExport.ExportList(await dal.SelectAllCountriesAsync()),
                        AppConstants.Model.Course => PdfExport.ExportList(await dal.SelectAllCoursesAsync()),
                        AppConstants.Model.Ingredient => PdfExport.ExportList(await dal.SelectAllIngredientsAsync()),
                        AppConstants.Model.Recipe => PdfExport.ExportList(await dal.SelectAllRecipesAsync()),
                        AppConstants.Model.Region => PdfExport.ExportList(await dal.SelectAllRegionsAsync()),
                        AppConstants.Model.Source => PdfExport.ExportList(await dal.SelectAllRecipeSourceAsync()),
                        _ => throw new NotImplementedException()
                    };
                    document.GeneratePdf(file_path_name);
                    break;
                #endregion
                default:
                    break;
            }
            FileStream str = new FileStream(file_path_name, FileMode.Open);
            byte[] content = new byte[str.Length];
            str.Read(content, 0, (int)str.Length);
            str.Close();
            System.IO.File.Delete(file_path_name);

Recipes/RecipesApp/Views/Partials/ThemeChanger.cshtml
<select id="theme_list" class="form-control">
    <option value="default">Basic</option>
    <option value="darkly">Darkly</option>
    <option value="sandstone">Sandstone</option>
    <option value="minty">Minty</option>
</select>

Recipes/RecipesApp/Views/Partials/_Empty.cshtml
@{
    var _t = (await CacheManagementService.TranslationsAsync())[Thread.CurrentThread.CurrentCulture.IetfLanguageTag];
}
<div class="d-flex justify-content-center align-content-center h-100">
    <p class="text">@_t[I18N.No_records_were_found]</p>
</div>

Recipes/RecipesApp/Views/Partials/_Head.cshtml
<link id="theme" href="~/css/default.css" rel="stylesheet" />
<link href="~/css/style.css" rel="stylesheet" />

@* Font-awesome *@
<link href="~/Libraries/font-awesome/all.css" rel="stylesheet" />

@* Dropify *@
<link href="~/Libraries/Dropify/css/dropify.min.css" rel="stylesheet" />

@* Noty *@
<script src="~/Libraries/Noty/noty.js"></script>
<link href="~/Libraries/Noty/noty.css" rel="stylesheet" />
<link href="~/Libraries/Noty/themes/bootstrap-v4.css" rel="stylesheet" />

@* Sweet alert *@
<link href="~/Libraries/sweetalert2/sweetalert2.min.css" rel="stylesheet" />
<script src="~/Libraries/sweetalert2/sweetalert2.all.min.js"></script>

@* Select2 *@
<link href="~/Libraries/select2/css/select2.css" rel="stylesheet" />

<style>
.select2-selection__clear {
    color: black;
}
</style>

Recipes/RecipesApp/Views/Partials/_Nav.cshtml
@using System.Linq;
@using System.Globalization;
@using Microsoft.Extensions.Caching.Memory;
@{
    var _t = (await CacheManagementService.TranslationsAsync())[Thread.CurrentThread.CurrentCulture.IetfLanguageTag];
}
<!-- Navigation-->
<nav class="navbar navbar-expand-lg navbar-dark bg-primary fixed-top px-4" id="sideNav">
    <a class="navbar-brand js-scroll-trigger" asp-action="Index" asp-controller="Home">
        <span><i class="fa fa-home"></i></span>
    </a>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse"
            data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent"
            aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
        <ul class="navbar-nav">
            <li class="nav-item">
                <a class="nav-link js-scroll-trigger" asp-action="Index" asp-controller="Recipe">@_t[I18N.Recipes]</a>
            </li>
            <li class="nav-item dropdown">
                <a class="nav-link dropdown-toggle" data-bs-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false" href="#">@_t[I18N.Management]</a>
                <div class="dropdown-menu">
                    <a id="author_link" class="dropdown-item" asp-action="Index" asp-controller="Author">@_t[I18N.Authors]</a>
                    <a id="category_link" class="dropdown-item" asp-action="Index" asp-controller="Category">@_t[I18N.Categories]</a>
                    <a id="region_link" class="dropdown-item" asp-action="Index" asp-controller="Region">@_t[I18N.Regions]</a>
                    <a id="country_link" class="dropdown-item" asp-action="Index" asp-controller="Country">@_t[I18N.Countries]</a>
                    <a id="source_link" class="dropdown-item" asp-action="Index" asp-controller="Source">@_t[I18N.Sources]</a>
                    <a id="course_link" class="dropdown-item" asp-action="Index" asp-controller="Course">@_t[I18N.Courses]</a>
                    <a id="ingredient_link" class="dropdown-item" asp-action="Index" asp-controller="Ingredient">@_t[I18N.Ingredients]</a>
                </div>
            </li>
            @if (User.Claims.Any(u => u.Type == System.Security.Claims.ClaimTypes.Role && u.Value == ModelsLibrary.Constants.AppConstants.Roles.Admin))
            {
                <li class="nav-item dropdown">
                    <a class="nav-link dropdown-toggle" data-bs-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false" href="#">Admin</a>
                    <div class="dropdown-menu">
                        <a id="author_link" class="dropdown-item" asp-action="Index" asp-controller="Culture">@_t[I18N.Localization]</a>
                        <a class="dropdown-item" asp-action="Index" asp-controller="Import">@_t[I18N.Import]</a>
                        <a class="dropdown-item" asp-action="ExportForm" asp-controller="Export">@_t[I18N.Export]</a>
                    </div>
                </li>                
            }
            <li class="nav-item dropdown">
                <a class="nav-link dropdown-toggle" data-bs-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false" href="#">@_t[I18N.Cultures]</a>
                <div class="dropdown-menu">
                    <form asp-action="SetCulture" asp-controller="Culture">
                        @Html.AntiForgeryToken()
                        @Html.DropDownList(
                        "culture",
                        (await RecipesApp.Services.CacheManagementService.CulturesAsync()).Select(cul =>
                        new SelectListItem {
                        Value = cul.Name,
                        Text = cul.Name,
                        Selected = Thread.CurrentThread.CurrentCulture.IetfLanguageTag == cul.Name
                        }),
                        new { @class="dropdown-item", onchange="this.form.submit()" })
                    </form>
                </div>
            </li>
            <li class="nav-item">
                <button class="nav-link" type="button" data-bs-toggle="offcanvas" data-bs-target="#offcanvasExample" aria-controls="offcanvasExample">
                    @_t[I18N.Themes]
                </button>
            </li>
        </ul>

        <div class="ml-auto navbar-nav">
            <form asp-action="Logout" asp-controller="Auth" method="post">
                @Html.AntiForgeryToken()
                <button class="btn btn-link text-white">Logout</button>
            </form>
        </div>

    </div>
</nav>

Recipes/RecipesApp/Views/Partials/_OffCanvas.cshtml
@{
    var _t = (await CacheManagementService.TranslationsAsync())[Thread.CurrentThread.CurrentCulture.IetfLanguageTag];
}

<div class="offcanvas offcanvas-end" tabindex="-1" id="offcanvasExample" aria-labelledby="offcanvasExampleLabel">
    <div class="offcanvas-header">
        <h5 class="offcanvas-title" id="offcanvasExampleLabel">@_t[I18N.Themes]</h5>
        <button type="button" class="btn-close" data-bs-dismiss="offcanvas" aria-label="Close"></button>
    </div>
    <div class="offcanvas-body">
        <div class="input-group mb-3">
            <div>
                <button data-theme="light" id="theme-changer-light" class="btn btn-primary theme_changer">
                    <i class="fa fa-sun text-white"></i>
                </button>
                <button data-theme="dark" id="theme-changer-dark" class="btn btn-primary theme_changer">
                    <i class="fa fa-moon text-white"></i>
                </button>
            </div>
            <partial name="~/Views/Partials/ThemeChanger.cshtml" />
        </div>
    </div>
</div>

Recipes/RecipesApp/Views/Partials/_ScriptUtilities.cshtml
<script src="~/js/ui-utilities/modal.js"></script>
<script src="~/js/ui-utilities/translations.js"></script>
<script src="~/js/ui-utilities/pagination.js"></script>

Recipes/RecipesApp/Views/Partials/_Scripts.cshtml
<script src="~/Libraries/jquery/jquery.min.js"></script>
<script src="~/colorthemes/js/themechange.js"></script>
<script src="~/js/bootstrap/bootstrap.bundle.min.js"></script>
<script src="~/Libraries/Dropify/js/dropify.min.js"></script>
<script src="~/Libraries/select2/js/select2.full.min.js"></script>
<script src="~/Libraries/select2/js/i18n/@(System.Threading.Thread.CurrentThread.CurrentCulture.Parent.Name).js"></script>